name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  FOUNDRY_PROFILE: ci

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
      - name: Install dev dependencies
        run: npm install

      - name: Run lint check
        run: npm run lint:check
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      - name: Check gas snapshots
        run: forge snapshot --check

      - name: Run tests
        run: forge test
